// <auto-generated />
using System;
using BRF.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BRF.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BRF.Api.Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BRF.Api.Domain.Article", b =>
                {
                    b.OwnsMany("BRF.Api.Domain.ArticleSection", "Content", b1 =>
                        {
                            b1.Property<Guid>("ArticleId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Text");

                            b1.Property<int>("Type");

                            b1.HasKey("ArticleId", "__synthesizedOrdinal");

                            b1.ToTable("Articles");

                            b1
                                .ToJson("Content")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");

                            b1.OwnsMany("BRF.Api.Domain.ArticleSectionImage", "Images", b2 =>
                                {
                                    b2.Property<Guid>("ArticleSectionArticleId");

                                    b2.Property<int>("ArticleSection__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Alt")
                                        .IsRequired();

                                    b2.Property<string>("Caption");

                                    b2.Property<string>("Src")
                                        .IsRequired();

                                    b2.HasKey("ArticleSectionArticleId", "ArticleSection__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Articles");

                                    b2.WithOwner()
                                        .HasForeignKey("ArticleSectionArticleId", "ArticleSection__synthesizedOrdinal");
                                });

                            b1.Navigation("Images");
                        });

                    b.Navigation("Content");
                });
#pragma warning restore 612, 618
        }
    }
}
